"""Update

Revision ID: 4bd00ef406e9
Revises: 8ad0cdd1f487
Create Date: 2025-02-23 15:37:32.770744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd00ef406e9'
down_revision = '8ad0cdd1f487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beers',
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('nr', sa.String(length=10), nullable=True),
    sa.Column('articleid', sa.String(length=10), nullable=True),
    sa.Column('articletype', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name2', sa.String(length=100), nullable=True),
    sa.Column('priceinclvat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumeml', sa.Integer(), nullable=True),
    sa.Column('priceperlitre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('introduced', sa.Date(), nullable=True),
    sa.Column('finaldelivery', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('packaging', sa.String(length=50), nullable=True),
    sa.Column('captype', sa.String(length=50), nullable=True),
    sa.Column('countryoforigin', sa.String(length=100), nullable=True),
    sa.Column('countryoforiginlandname', sa.String(length=100), nullable=True),
    sa.Column('producer', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('productionyear', sa.String(length=4), nullable=True),
    sa.Column('testedproductionyear', sa.String(length=4), nullable=True),
    sa.Column('alcoholstrength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('assortment', sa.String(length=50), nullable=True),
    sa.Column('organic', sa.Boolean(), nullable=True),
    sa.Column('kosher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('beer_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('credentials', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('beers_sold',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.beer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'canceled', name='order_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payments',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('vip_customers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.beer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('vip_customers')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('beers_sold')
    op.drop_table('users')
    op.drop_table('beers')
    # ### end Alembic commands ###
