beers = [
    {
        "Name": "Punk IPA",
        "Producer/Brewery": "BrewDog",
        "Country": "Scotland",
        "Type": "IPA",
        "Strength": "5.6%",
        "Serving size": "Bottle",
        "Price": "55 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.6%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Heineken",
        "Producer/Brewery": "Heineken International",
        "Country": "Netherlands",
        "Type": "Lager",
        "Strength": "5.0%",
        "Serving size": "Tap",
        "Price": "50 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.0%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Guinness Draught",
        "Producer/Brewery": "Guinness",
        "Country": "Ireland",
        "Type": "Stout",
        "Strength": "4.2%",
        "Serving size": "Tap",
        "Price": "60 SEK",
        "Allergens": ["Gluten", "Lactose"],
        "Alcohol Content": "4.2%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Carlsberg",
        "Producer/Brewery": "Carlsberg Group",
        "Country": "Denmark",
        "Type": "Pilsner",
        "Strength": "5.0%",
        "Serving size": "Bottle",
        "Price": "48 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.0%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Sierra Nevada Pale Ale",
        "Producer/Brewery": "Sierra Nevada Brewing Co.",
        "Country": "USA",
        "Type": "Pale Ale",
        "Strength": "5.6%",
        "Serving size": "Bottle",
        "Price": "65 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.6%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    }
]
wines = [
    {
        "Name": "Château Margaux",
        "Year": "2015",
        "Producer": "Château Margaux",
        "Type": "Red",
        "Grape": "Cabernet Sauvignon",
        "Serving size": "Bottle",
        "Price": "2500 SEK",
        "Allergens": [],
        "Alcohol Content": "13.5%",
        "Tannins": "High",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Dom Pérignon",
        "Year": "2012",
        "Producer": "Moët & Chandon",
        "Type": "Champagne",
        "Grape": "Chardonnay, Pinot Noir",
        "Serving size": "Bottle",
        "Price": "2000 SEK",
        "Allergens": [],
        "Alcohol Content": "12.5%",
        "Tannins": "Low",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Cloudy Bay Sauvignon Blanc",
        "Year": "2021",
        "Producer": "Cloudy Bay",
        "Type": "White",
        "Grape": "Sauvignon Blanc",
        "Serving size": "Glass",
        "Price": "150 SEK",
        "Allergens": [],
        "Alcohol Content": "12.0%",
        "Tannins": "Low",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Barolo",
        "Year": "2016",
        "Producer": "Pio Cesare",
        "Type": "Red",
        "Grape": "Nebbiolo",
        "Serving size": "Bottle",
        "Price": "1800 SEK",
        "Allergens": [],
        "Alcohol Content": "14.0%",
        "Tannins": "High",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Riesling Kabinett",
        "Year": "2020",
        "Producer": "Dr. Loosen",
        "Type": "White",
        "Grape": "Riesling",
        "Serving size": "Glass",
        "Price": "130 SEK",
        "Allergens": [],
        "Alcohol Content": "11.5%",
        "Tannins": "Medium",
        "VIP": False,
        "Stock": 10
    }
]
cocktails = [
    {
        "Name": "Margarita",
        "Strength": "Strong",
        "Contents/Recipe": "Tequila, Triple Sec, Lime Juice, Salt",
        "Serving size": "Glass",
        "Price": "120 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "40%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Mojito",
        "Strength": "Medium",
        "Contents/Recipe": "White Rum, Lime, Mint, Sugar, Soda Water",
        "Serving size": "Glass",
        "Price": "110 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "25%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Old Fashioned",
        "Strength": "Strong",
        "Contents/Recipe": "Bourbon, Sugar, Angostura Bitters, Orange Peel",
        "Serving size": "Glass",
        "Price": "130 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "35%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Negroni",
        "Strength": "Strong",
        "Contents/Recipe": "Gin, Campari, Sweet Vermouth",
        "Serving size": "Glass",
        "Price": "125 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "30%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    },
    {
        "Name": "Piña Colada",
        "Strength": "Medium",
        "Contents/Recipe": "White Rum, Coconut Cream, Pineapple Juice",
        "Serving size": "Glass",
        "Price": "115 SEK",
        "Allergens": ["Coconut"],
        "Alcohol Content": "20%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10
    }
]
