LANGUAGE = {
    "English": {
        "login": "Log in",
        "logout": "Log out",
        "menu": "Menu",
        "cart": "Shopping Cart",
        "checkout": "Checkout",
        "undo": "Undo",
        "redo": "redo",
        "username": "Username",
        "password": "Password",
        "beer menu": "Beer Menu",
        "order": "Order",
        "guest_btn": "Continue as a Guest",
        "search": "Search",
        "add friends": "Add Friends",
        "confirm": "Confirm",
        "language": "Language"
    },
    "Svenska": {
        "login": "Logga in",
        "logout": "Logga ut",
        "menu": "Meny",
        "cart": "Kundvagn",
        "checkout": "Betala",
        "undo": "Ångra",
        "redo": "Gör igen",
        "username": "Användarnamn",
        "password": "Lösenord",
        "beer menu": "Ölmeny",
        "order": "Beställ",
        "guest_btn": "Fortsätt som gäst",
        "search": "Sök",
        "add friends": "Lägg till vänner",
        "confirm": "Bekräfta",
        "language": "Språk"
    },
    "中文": {
        "login": "登录",
        "logout": "登出",
        "menu": "菜单",
        "cart": "购物车",
        "checkout": "结账",
        "undo": "撤消",
        "redo": "重做",
        "username": "用户名",
        "password": "密码",
        "beer menu": "酒单",
        "order": "点餐",
        "guest_btn": "以访客身份继续",
        "search": "搜索",
        "add friends": "添加朋友",
        "confirm": "确认",
        "language": "语言"
    }
}
