LANGUAGE = {
    "English": {
        "index": "0",
        "login": "Log in",
        "logout": "Log out",
        "menu": "Menu",
        "cart": "Shopping Cart",
        "checkout": "Checkout",
        "undo": "Undo",
        "redo": "Redo",
        "username": "Username",
        "password": "Password",
        "beer menu": "Beer Menu",
        "order": "Order",
        "guest_btn": "Continue as a Guest",
        "search": "Search",
        "add friends": "Add Friends",
        "confirm": "Confirm",
        "language": "Language",
        "resolution": "Display Resolution",
        "total": "Total payment",
        "person": "Person",
        "confirm_order": "Confirm the order?",
        "yes": "Yes",
        "no": "No",
    },
    "Română": {
        "index": "1",
        "login": "Logare",
        "logout": "Delogare",
        "menu": "Meniu",
        "cart": "Coș de cumpărături",
        "checkout": "Total de plată",
        "undo": "Desface",
        "redo": "Reface",
        "username": "Utilizator",
        "password": "Parolă",
        "beer menu": "Meniu de băuturi",
        "order": "Comanda",
        "guest_btn": "Continuă ca vizitator",
        "search": "Caută",
        "add friends": "Adaugă prieteni",
        "confirm": "Confirmă",
        "language": "Limbă",
        "resolution": "Rezoluție ecran",
        "total": "Total de plată",
        "person": "Persoană",
        "confirm_order": "Confirmi comanda?",
        "yes": "Da",
        "no": "Nu",
    },
    "中文": {
        "index": "2",
        "login": "登录",
        "logout": "登出",
        "menu": "菜单",
        "cart": "购物车",
        "checkout": "结账",
        "undo": "撤消",
        "redo": "重做",
        "username": "用户名",
        "password": "密码",
        "beer menu": "酒单",
        "order": "点餐",
        "guest_btn": "以访客身份继续",
        "search": "搜索",
        "add friends": "添加朋友",
        "confirm": "确认",
        "language": "语言",
        "resolution": "显示分辨率",
        "total": "总付款",
        "person": "人",
        "confirm_order": "确认订单？",
        "yes": "是的",
        "no": "不",
    }
}