# =============================================================================
# menu.py
# =============================================================================
# @AUTHOR: Ting-Hsuan Lien, Yuxie Liu
# @VERSION: X.0
# @DATE: latest edit - 23.03.2025
#
# @PURPOSE: List to store all the items from the menu (beverages from all
# three types, foods)
# =======================================================
menu = [
    {
        "Name": "Wagyu Beef Sliders",
        "Ingredients": "Wagyu Beef, Brioche Bun, Truffle Mayo, Arugula, Caramelized Onion".split(),
        "Price": "250 SEK",
        "Allergens": ["Gluten", "Egg", "Lactose"],
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Lobster Mac & Cheese",
        "Ingredients": "Pasta, Lobster, Cheddar, Gruyère, Parmesan, Cream, Garlic, Herbs".split(),
        "Price": "275 SEK",
        "Allergens": ["Gluten", "Lactose"],
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Black Truffle Risotto",
        "Ingredients": "Arborio Rice, Black Truffle, Parmesan, Butter, White wine".split(),
        "Price": "260 SEK",
        "Allergens": ["Lactose"],
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Seared Tuna Tataki",
        "Ingredients": "Tuna, Soy Sauce, Ginger, Sesame Seeds, Scallions".split(),
        "Price": "240 SEK",
        "Allergens": ["Fish", "Sesame", "Soy"],
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Foie Gras Crostini",
        "Ingredients": "Foie Gras, Toasted Bread, Fig Jam, Microgreens".split(),
        "Price": "280 SEK",
        "Allergens": ["Gluten"],
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Samuel Adams Utopias",
        "Producer/Brewery": "Boston beer Company",
        "Country": "USA",
        "Type": "Strong Ale",
        "Strength": "28%",
        "Serving size": "Bottle",
        "Price": "950 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "28%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Westvleteren 12",
        "Producer/Brewery": "Westvleteren Brewery",
        "Country": "Belgium",
        "Type": "Quadrupel",
        "Strength": "10.2%",
        "Serving size": "Bottle",
        "Price": "450 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "10.2%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "The Bruery Black Tuesday",
        "Producer/Brewery": "The Bruery",
        "Country": "USA",
        "Type": "Imperial Stout",
        "Strength": "19.5%",
        "Serving size": "Bottle",
        "Price": "600 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "19.5%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Goose Island Bourbon County",
        "Producer/Brewery": "Goose Island beer Co.",
        "Country": "USA",
        "Type": "Stout",
        "Strength": "14.7%",
        "Serving size": "Bottle",
        "Price": "350 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "14.7%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Schorschbock 57",
        "Producer/Brewery": "Schorschbräu",
        "Country": "Germany",
        "Type": "Eisbock",
        "Strength": "57.5%",
        "Serving size": "Bottle",
        "Price": "1200 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "57.5%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Château Pétrus",
        "Year": "2018",
        "Producer": "Château Pétrus",
        "Type": "Red",
        "Grape": "Merlot",
        "Serving size": "Bottle",
        "Price": "30000 SEK",
        "Allergens": [],
        "Alcohol Content": "14.5%",
        "Tannins": "High",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Screaming Eagle Cabernet Sauvignon",
        "Year": "2019",
        "Producer": "Screaming Eagle",
        "Type": "Red",
        "Grape": "Cabernet Sauvignon",
        "Serving size": "Bottle",
        "Price": "28000 SEK",
        "Allergens": [],
        "Alcohol Content": "14.8%",
        "Tannins": "High",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Domaine de la Romanée-Conti",
        "Year": "2020",
        "Producer": "DRC",
        "Type": "Red",
        "Grape": "Pinot Noir",
        "Serving size": "Bottle",
        "Price": "40000 SEK",
        "Allergens": [],
        "Alcohol Content": "13.5%",
        "Tannins": "Medium",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Salon Cuvée 'S' Le Mesnil",
        "Year": "2008",
        "Producer": "Salon",
        "Type": "Champagne",
        "Grape": "Chardonnay",
        "Serving size": "Bottle",
        "Price": "12000 SEK",
        "Allergens": [],
        "Alcohol Content": "12%",
        "Tannins": "Low",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Château d'Yquem",
        "Year": "2009",
        "Producer": "Château d'Yquem",
        "Type": "Dessert",
        "Grape": "Sémillon, Sauvignon Blanc",
        "Serving size": "Bottle",
        "Price": "9000 SEK",
        "Allergens": [],
        "Alcohol Content": "14%",
        "Tannins": "Low",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "The Billionaire",
        "Strength": "Strong",
        "Contents/Recipe": "Bourbon, Absinthe, Lemon Juice, Grenadine".split(),
        "Serving size": "Glass",
        "Price": "350 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "35%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Gold Fashioned",
        "Strength": "Strong",
        "Contents/Recipe": "Gold-infused Whiskey, Maple Syrup, Angostura Bitters".split(),
        "Serving size": "Glass",
        "Price": "400 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "40%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Truffle Martini",
        "Strength": "Strong",
        "Contents/Recipe": "Truffle-infused Vodka, Dry Vermouth".split(),
        "Serving size": "Glass",
        "Price": "450 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "38%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Royal Negroni",
        "Strength": "Strong",
        "Contents/Recipe": "Premium Gin, Campari, Vermouth Rosso, Gold Flakes".split(),
        "Serving size": "Glass",
        "Price": "380 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "35%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Vintage Sidecar",
        "Strength": "Strong",
        "Contents/Recipe": "Vintage Cognac, Cointreau, Lemon Juice".split(),
        "Serving size": "Glass",
        "Price": "420 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "38%",
        "Tannins": "None",
        "VIP": True,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Punk IPA",
        "Producer/Brewery": "BrewDog",
        "Country": "Scotland",
        "Type": "IPA",
        "Strength": "5.6%",
        "Serving size": "Bottle",
        "Price": "55 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.6%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Heineken",
        "Producer/Brewery": "Heineken International",
        "Country": "Netherlands",
        "Type": "Lager",
        "Strength": "5.0%",
        "Serving size": "Tap",
        "Price": "50 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.0%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Guinness Draught",
        "Producer/Brewery": "Guinness",
        "Country": "Ireland",
        "Type": "Stout",
        "Strength": "4.2%",
        "Serving size": "Tap",
        "Price": "60 SEK",
        "Allergens": ["Gluten", "Lactose"],
        "Alcohol Content": "4.2%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Carlsberg",
        "Producer/Brewery": "Carlsberg Group",
        "Country": "Denmark",
        "Type": "Pilsner",
        "Strength": "5.0%",
        "Serving size": "Bottle",
        "Price": "48 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.0%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Sierra Nevada Pale Ale",
        "Producer/Brewery": "Sierra Nevada Brewing Co.",
        "Country": "USA",
        "Type": "Pale Ale",
        "Strength": "5.6%",
        "Serving size": "Bottle",
        "Price": "65 SEK",
        "Allergens": ["Gluten"],
        "Alcohol Content": "5.6%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "beer"
    },
    {
        "Name": "Château Margaux",
        "Year": "2015",
        "Producer": "Château Margaux",
        "Type": "Red",
        "Grape": "Cabernet Sauvignon",
        "Serving size": "Bottle",
        "Price": "2500 SEK",
        "Allergens": [],
        "Alcohol Content": "13.5%",
        "Tannins": "High",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Dom Pérignon",
        "Year": "2012",
        "Producer": "Moët & Chandon",
        "Type": "Champagne",
        "Grape": "Chardonnay, Pinot Noir",
        "Serving size": "Bottle",
        "Price": "2000 SEK",
        "Allergens": [],
        "Alcohol Content": "12.5%",
        "Tannins": "Low",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Cloudy Bay Sauvignon Blanc",
        "Year": "2021",
        "Producer": "Cloudy Bay",
        "Type": "White",
        "Grape": "Sauvignon Blanc",
        "Serving size": "Glass",
        "Price": "150 SEK",
        "Allergens": [],
        "Alcohol Content": "12.0%",
        "Tannins": "Low",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Barolo",
        "Year": "2016",
        "Producer": "Pio Cesare",
        "Type": "Red",
        "Grape": "Nebbiolo",
        "Serving size": "Bottle",
        "Price": "1800 SEK",
        "Allergens": [],
        "Alcohol Content": "14.0%",
        "Tannins": "High",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Riesling Kabinett",
        "Year": "2020",
        "Producer": "Dr. Loosen",
        "Type": "White",
        "Grape": "Riesling",
        "Serving size": "Glass",
        "Price": "130 SEK",
        "Allergens": [],
        "Alcohol Content": "11.5%",
        "Tannins": "Medium",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "wine"
    },
    {
        "Name": "Margarita",
        "Strength": "Strong",
        "Contents/Recipe": "Tequila, Triple Sec, Lime Juice, Salt".split(),
        "Serving size": "Glass",
        "Price": "120 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "40%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Mojito",
        "Strength": "Medium",
        "Contents/Recipe": "White Rum, Lime, Mint, Sugar, Soda Water".split(),
        "Serving size": "Glass",
        "Price": "110 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "25%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Old Fashioned",
        "Strength": "Strong",
        "Contents/Recipe": "Bourbon, Sugar, Angostura Bitters, Orange Peel".split(),
        "Serving size": "Glass",
        "Price": "130 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "35%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Negroni",
        "Strength": "Strong",
        "Contents/Recipe": "Gin, Campari, Sweet Vermouth".split(),
        "Serving size": "Glass",
        "Price": "125 SEK",
        "Allergens": ["None"],
        "Alcohol Content": "30%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Piña Colada",
        "Strength": "Medium",
        "Contents/Recipe": "White Rum, Coconut Cream, Pineapple Juice".split(),
        "Serving size": "Glass",
        "Price": "115 SEK",
        "Allergens": ["Coconut"],
        "Alcohol Content": "20%",
        "Tannins": "None",
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "cocktail"
    },
    {
        "Name": "Buffalo Wings",
        "Ingredients": "Chicken Wings, Hot Sauce, Butter, Vinegar, Garlic, Celery, Blue Cheese Dressing".split(),
        "Price": "125 SEK",
        "Allergens": ["Lactose"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Nachos with Cheese & Jalapeños",
        "Ingredients": "Corn Chips, Cheddar Cheese, Jalapeños, Sour Cream, Salsa, Guacamole".split(),
        "Price": "110 SEK",
        "Allergens": ["Lactose"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Sliders (Mini Burgers)",
        "Ingredients": "Beef Patty, Cheddar Cheese, Burger Bun, Lettuce, Tomato, Pickles, Mayo, Ketchup, Mustard".split(),
        "Price": "140 SEK",
        "Allergens": ["Gluten", "Lactose", "Egg"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Fish & Chips",
        "Ingredients": "Cod Fillet, Batter, French Fries, Tartar Sauce, Lemon, Salt, Vinegar".split(),
        "Price": "155 SEK",
        "Allergens": ["Gluten", "Fish", "Egg"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Mozzarella Sticks",
        "Ingredients": "Mozzarella Cheese, Bread Crumbs, Egg, Flour, Marinara Sauce".split(),
        "Price": "120 SEK",
        "Allergens": ["Gluten", "Lactose", "Egg"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Loaded Potato Skins",
        "Ingredients": "Potato Skins, Cheddar Cheese, Bacon, Sour Cream, Green Onions".split(),
        "Price": "130 SEK",
        "Allergens": ["Lactose"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Onion Rings",
        "Ingredients": "Onion, Flour, Bread Crumbs, Egg, Milk, Salt, Pepper".split(),
        "Price": "95 SEK",
        "Allergens": ["Gluten", "Lactose", "Egg"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "BBQ Pulled Pork Sandwich",
        "Ingredients": "Pulled Pork, BBQ Sauce, Burger Bun, Coleslaw (Cabbage, Carrot, Mayo, Vinegar)".split(),
        "Price": "145 SEK",
        "Allergens": ["Gluten", "Egg"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Garlic Parmesan Fries",
        "Ingredients": "French Fries, Garlic, Parmesan Cheese, Olive Oil, Salt, Pepper".split(),
        "Price": "85 SEK",
        "Allergens": ["Lactose"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    },
    {
        "Name": "Jalapeño Poppers",
        "Ingredients": "Jalapeños, Cream Cheese, Bread Crumbs, Egg, Flour".split(),
        "Price": "115 SEK",
        "Allergens": ["Gluten", "Lactose", "Egg"],
        "VIP": False,
        "Stock": 10,
        "Hidden": False,
        "Tag": "food"
    }
]